"""Addind Notes Fields table

Revision ID: 04465addde73
Revises: 5b20ff98adf3
Create Date: 2023-10-17 09:07:09.711089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04465addde73'
down_revision = '5b20ff98adf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atcCode', sa.String(length=10), nullable=True),
    sa.Column('prohibitedOUTCompetition', sa.String(length=15), nullable=True),
    sa.Column('prohibitedINCompetition', sa.String(length=15), nullable=True),
    sa.Column('prohibitedClass', sa.String(length=10), nullable=True),
    sa.Column('notesLV', sa.Text(), nullable=True),
    sa.Column('sportsINCompetitionLV', sa.Text(), nullable=True),
    sa.Column('sportsOUTCompetitionLV', sa.Text(), nullable=True),
    sa.Column('notesEN', sa.Text(), nullable=True),
    sa.Column('sportsINCompetitionEN', sa.Text(), nullable=True),
    sa.Column('sportsOUTCompetitionEN', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atcCode')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes_fields')
    # ### end Alembic commands ###
