"""adding form column on notesfields

Revision ID: 4dbb29fb5f78
Revises: manual_remove_atc
Create Date: 2025-01-15 16:20:23.977028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dbb29fb5f78'
down_revision = 'manual_remove_atc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form', sa.Text(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes_fields', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('form')

    # ### end Alembic commands ###
