"""Adding columns for csv file preparation

Revision ID: 5b1d7b9f19da
Revises: ecefb3a2ff96
Create Date: 2023-10-11 13:47:50.149216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b1d7b9f19da'
down_revision = 'ecefb3a2ff96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('added_medication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prohibitedOUTCompetition', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prohibitedINCompetition', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notesLV', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('sportsINCompetitionLV', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('sportsOUTCompetitionLV', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('notesEN', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('sportsINCompetitionEN', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('sportsOUTCompetitionEN', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('added_medication', schema=None) as batch_op:
        batch_op.drop_column('sportsOUTCompetitionEN')
        batch_op.drop_column('sportsINCompetitionEN')
        batch_op.drop_column('notesEN')
        batch_op.drop_column('sportsOUTCompetitionLV')
        batch_op.drop_column('sportsINCompetitionLV')
        batch_op.drop_column('notesLV')
        batch_op.drop_column('prohibitedINCompetition')
        batch_op.drop_column('prohibitedOUTCompetition')

    # ### end Alembic commands ###
