"""Changing prohibited column type

Revision ID: 5b20ff98adf3
Revises: dd2434380a94
Create Date: 2023-10-17 07:33:28.961511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b20ff98adf3'
down_revision = 'dd2434380a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('added_medication', schema=None) as batch_op:
        batch_op.alter_column('regNumber',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('prohibitedOUTCompetition',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=15),
               existing_nullable=True)
        batch_op.alter_column('prohibitedINCompetition',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('added_medication', schema=None) as batch_op:
        batch_op.alter_column('prohibitedINCompetition',
               existing_type=sa.String(length=15),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('prohibitedOUTCompetition',
               existing_type=sa.String(length=15),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('regNumber',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###
