"""empty message

Revision ID: b70eb8201a46
Revises: 04465addde73
Create Date: 2023-12-05 16:01:37.849824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b70eb8201a46'
down_revision = '04465addde73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searched_medication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atcCode', sa.String(length=10), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('regNumber', sa.String(length=20), nullable=True),
    sa.Column('form', sa.Text(), nullable=True),
    sa.Column('activeSubstance', sa.Text(), nullable=True),
    sa.Column('include', sa.Boolean(), nullable=True),
    sa.Column('userChecked', sa.Boolean(), nullable=True),
    sa.Column('prohibitedOUTCompetition', sa.String(length=15), nullable=True),
    sa.Column('prohibitedINCompetition', sa.String(length=15), nullable=True),
    sa.Column('prohibitedClass', sa.String(length=10), nullable=True),
    sa.Column('notesLV', sa.Text(), nullable=True),
    sa.Column('sportsINCompetitionLV', sa.Text(), nullable=True),
    sa.Column('sportsOUTCompetitionLV', sa.Text(), nullable=True),
    sa.Column('notesEN', sa.Text(), nullable=True),
    sa.Column('sportsINCompetitionEN', sa.Text(), nullable=True),
    sa.Column('sportsOUTCompetitionEN', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('searched_medication')
    # ### end Alembic commands ###
