"""Adding userChecked column

Revision ID: bb48781d968e
Revises: 5b1d7b9f19da
Create Date: 2023-10-12 14:19:35.787271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb48781d968e'
down_revision = '5b1d7b9f19da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('added_medication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userChecked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('added_medication', schema=None) as batch_op:
        batch_op.drop_column('userChecked')

    # ### end Alembic commands ###
