"""Added table for medication

Revision ID: d0ef7e1138ef
Revises: 9e852a565f03
Create Date: 2023-04-12 13:23:06.510296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ef7e1138ef'
down_revision = '9e852a565f03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('added_medication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('regNumber', sa.String(length=64), nullable=True),
    sa.Column('atcCode', sa.String(length=64), nullable=True),
    sa.Column('form', sa.Text(), nullable=True),
    sa.Column('activeSubstance', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('added_medication')
    # ### end Alembic commands ###
